# Generated by Django 4.2.2 on 2023-07-11 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_brand_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimages',
            old_name='Product',
            new_name='product',
        ),
    ]
